# Q1: Questions on Basic NumPy Array 

### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [4]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
print(np.flip(arr))

[5 4 6 3 2 1]


### (b)Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
### NumPy in-built methods

In [ ]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(array1.flatten())
prnt(np.ravel(array1))

### (c) Compare the following numpy arrays: 
### arr1 = np.array([[1, 2], [3, 4]]) 
### arr2 = np.array([[1, 2], [3, 4]]) 

In [10]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
print(arr1==arr2)

[[ True  True]
 [ True  True]]


### (d) Find the most frequent value and their indice(s) in the following arrays: 
### i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
### ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [13]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
counts1=np.bincount(x)
counts2=np.bincount(y)
print(np.max(counts1),np.argmax(counts1))
print(np.max(counts2),np.argmax(counts2))

5 1
3 1


### (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
### i. Sum of all elements 
### ii. Sum of all elements row-wise
### iii. Sum of all elements column-wise

In [20]:
gfg = np.array([[4, 1, 9], [12, 3, 1] ,[4, 5, 6]])
print("sum ",np.sum(gfg))
print("sum row wise ",np.sum(gfg,axis=1))
print("sum column wise ",np.sum(gfg,axis=0))

45
[14 16 15]
[20  9 16]


### (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
### i. Sum of diagonal elements 
### ii. Eigen values of matrix
### iii. Eigen vectors of matrix 
### iv. Inverse of matrix
### v. Determinant of matrix 

In [23]:
gfg= np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
sum_diag= np.trace(gfg)
print("Sum of diagonal elements:", sum_diag)
eigen_values, eigen_vectors = np.linalg.eig(gfg)
print("Eigen values:", eigen_values)
print("Eigen vectors:", eigen_vectors)
inverse_matrix = np.linalg.inv(gfg)
print("Inverse matrix:\n", inverse_matrix)
determinant = np.linalg.det(gfg)
print("Determinant:", determinant)


Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


### (g) Multiply the following matrices and also find covariance between matrices using NumPy: 
### i. p = [[1, 2], [2, 3]] 
### q = [[4, 5], [6, 7]] 
### ii. p = [[1, 2], [2, 3], [4, 5]] 
### q = [[4, 5, 1], [6, 7, 2]] 

In [4]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
mul1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)
print("Product:\n", mul1)
print("Covariance:\n", cov1)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
"""mul2 = np.dot(p2, q2)
cov2 = np.cov(p2.T, q2.T)
print("Product:\n", mul2)
print("Covariance:\n", cov2)"""


Product:
 [[16 19]
 [26 31]]
Covariance:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


'mul2 = np.dot(p2, q2)\ncov2 = np.cov(p2.T, q2.T)\nprint("Product:\n", mul2)\nprint("Covariance:\n", cov2)'

In [ ]:
(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product? 

# Q2: Based on NumPy Mathematics and Statistics

### (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
### i. Find element-wise absolute value
### ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
### row. 
### iii. Mean, Median and Standard Deviation of flattened array, of each column, and 
### each row

In [8]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)
flat = array.flatten()
print("25th, 50th, 75th (Flat):", np.percentile(flat, [25, 50, 75]))
print("Column:", np.percentile(array, [25, 50, 75], axis=0))
print("Row:", np.percentile(array, [25, 50, 75], axis=1))
print("Mean (Flat):", np.mean(flat))
print("Median (Flat):", np.median(flat))
print("Std (Flat):", np.std(flat))

[[1 2 3]
 [4 5 6]]
25th, 50th, 75th (Flat): [-3.5 -0.5  2.5]
Column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (Flat): -0.5
Median (Flat): -0.5
Std (Flat): 3.8622100754188224


### (b) for the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
### and truncated value, rounded values 

In [9]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


# Q3: Based on Searching and Sorting 

### (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
### i. Sorted array 
### ii.Indices of sorted array 
### iii. 4 smallest elements 
### iv. 5 largest elements

In [10]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_arr = np.sort(array)
indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]
print("Sorted:", sorted_arr)
print("Indices:", indices)
print("Smallest 4:", smallest_4)
print("Largest 5:", largest_5)

Sorted: [ 10  16  16  52  54  62 453]
Indices: [0 3 4 1 5 2 6]
Smallest 4: [10 16 16 52]
Largest 5: [ 16  52  54  62 453]


### (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
### i. Integer elements only 
### ii. Float elements only  

In [11]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]
print("Integers:", int_elements)
print("Floats:", float_elements)

Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]
